site_name: SEGY-SAK Documentation
site_description: SEGY file loading in Python using Xarray
site_author: Tony Hallam
site_url: https://segysak.readthedocs.io/
repo_name: trhallam/segysak
repo_url: https://github.com/trhallam/segysak
edit_uri: edit/main/docs
copyright: "Tony Hallam"

docs_dir: docs
theme:
  name: material
  custom_dir: docs/overrides
  language: "en"
  features:
    - navigations.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - content.action.edit
    - content.action.view
    - content.code.copy
  palette:
    primary: teal
  icon:
    repo: fontawesome/brands/github
use_directory_urls: false

# Customization
extra:
  version:
    provider: mike

extra_css:
  - stylesheets/fix-xarray-rep.css

watch:
  - docs
  - examples

markdown_extensions:
  - markdown.extensions.attr_list:
  - markdown.extensions.admonition:
  - markdown.extensions.footnotes:
  - markdown.extensions.md_in_html:
  - markdown.extensions.tables:
  - codehilite:
      guess_lang: false
  - markdown.extensions.toc:
      permalink: false
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
      auto_title: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
      base_path:
        - docs/.snippets
      auto_append:
        - links.txt
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

# extra_javascript:
#   - javascripts/mathjax.js
#   - https://polyfill.io/v3/polyfill.min.js?features=es6
#   - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - simple:
      include: [".md", ".cff", "LICENSE", ".ipynb"]
  - autorefs
  - mkdocs-jupyter:
      execute: false
      kernel_name: python3
      include_source: True
      include: ["examples/*.ipynb"]
      remove_tag_config:
        remove_input_tags:
          - hide-code
      # execute_ignore:
  - mkdocstrings:
      default_handler: python
  - mike:
      alias_type: symlink
      redirect_template: null
      deploy_prefix: ""
      canonical_version: latest
      version_selector: true
      css_dir: css
      javascript_dir: js

nav:
  - Home:
      - About: index.md
      - Walkthrough:
          - Installation: installation.md
          - Quickstart: quickstart.md
          - Upgrading to v0.5: upgrading.md
      - Learn:
          - Why SEGYSAK: why-segysak.md
          - Xarray SEISNC: seisnc.md
          - History: history.md
      - Community:
          - Discussions: https://github.com/trhallam/segysak/discussions
          - Issue Tracker: https://github.com/trhallam/segysak/issues
          - Contributing: contributing.md
  - Examples:
      - About: examples_about.md
      - Quick Overview: examples/QuickOverview.ipynb
      - Segysak Basics: examples/example_segysak_basics.ipynb
      - SEG-Y Headers: examples/example_segy_headers.ipynb
      - Arbitrary Line: examples/example_extract_arbitrary_line.ipynb
      - Amplitude Extraction: examples/example_amplitude_extraction_displays.ipynb
      - Data on a Horizon: examples/example_extract_data_on_a_horizon.ipynb
      - Vectorize SEG-Y for ML: examples/example_segysak_segy_vectorisation.ipynb
      - Working with Gathers: examples/example_working_with_3d_gathers.ipynb
      - Merge two surveys: examples/example_merge_surveys.ipynb
      - Lazy operations with Dask: examples/example_segysak_dask.ipynb
  - CLI:
      - About: cli/about.md
      - Pipelines: cli/command-pipelines.md
      - Reference: cli/command-line-ref.md
  - Tutorial: tutorial.md
  - Meta:
      - FAQ: meta/faq.md
  - Reference:
      - About: api.md
      - SEISNC conventions: seisnc-standard.md
      - Inspecting SEG-Y: api/segy_inspecting.md
      - SEG-Y text header operations: api/segy_text.md
      - SEG-Y via Xarray: api/segy_xarray.md
      - Xarray Accessor modules: api/xarray_new.md
      - Survey Geometry: api/geometry.md
      - Package Utils: api/utils.md
      - Depreciated Loading SEG-Y: api/segy_loading.md
      - Depreciated Writing SEG-Y: api/segy_writing.md
      - Depreciated Xarray Accessor modules: api/xarray_accessor.md
