name: docs-build-publish

on:
  release:
    types:
      - created
      - edited
    branches: main
  workflow_dispatch:

jobs:
  notebooks:
    name: "Build the notebooks for the docs"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install wheel
          python -m pip install -r requirements.txt

      - name: Install package
        run: python setup.py install

      - name: What is my env spec?
        run: pip list

      - name: What are my kernels?
        run: jupyter kernelspec list

      - name: Execute the notebooks
        run: |
          jupytext --to ipynb --execute examples/*.py
          mv examples/*.ipynb examples/notebooks/.

      - uses: actions/upload-artifact@v2
        with:
          name: example-notebooks-${{ github.sha }}
          path: examples/notebooks

      - name: Trigger RTDs build
        uses: dfm/rtds-action@v1
        with:
          webhook_url: ${{ secrets.RTDS_WEBHOOK_URL }}
          webhook_token: ${{ secrets.RTDS_WEBHOOK_TOKEN }}
          commit_ref: ${{ github.ref }}
