name: docs-build-publish

on:
  release:
    types:
      - created
      - edited
    branches: main
  workflow_dispatch:

jobs:
  notebooks:
    name: "Build the notebooks for the docs"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Need to fetch more than the last commit so that setuptools_scm can
          # create the correct version string. If the number of commits since
          # the last release is greater than this, the version will still be
          # wrong. Increase if necessary.
          fetch-depth: 100
          # The GitHub token is preserved by default but this job doesn't need
          # to be able to push to GitHub.
          persist-credentials: false
          # get zgy submodule
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install wheel
          python -m pip install -r requirements.txt

      - name: Install package
        run: python setup.py install

      - name: What is my env spec?
        run: pip list

      - name: What are my kernels?
        run: jupyter kernelspec list

      - name: Execute the notebooks
        run: |
          xvfb-run jupytext --to ipynb --execute examples/*.py
          mv examples/*.ipynb examples/notebooks/.

      - name: Artifact Upload
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: example-notebooks-${{ github.sha }}
          path: examples/notebooks

      - name: Trigger RTDs build
        if: success()
        uses: dfm/rtds-action@v1
        with:
          webhook_url: ${{ secrets.RTDS_WEBHOOK_URL }}
          webhook_token: ${{ secrets.RTDS_WEBHOOK_TOKEN }}
          commit_ref: ${{ github.ref }}
