name: Publish docs via GitHub Pages

on: [push, pull_request]

env:
  PACKAGE: segysak

jobs:
  mkdocs_build_test_deploy:
    name: build mkdocs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update clone config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch origin gh-pages --depth=1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # required to use caching because it depends on requirements.txt
      - name: Setup Hatch
        run: |
          python -m pip install --upgrade pip
          python -m pip install hatch

      - name: Build docs examples
        run: |
          echo "HATCH_VERSION=$(hatch version)" >> $GITHUB_ENV
          hatch run docs:build-examples
          hatch run docs:cli-snippets

      - name: Deploy mkdocs
        if: success() && github.event_name == 'push' && github.ref_name == 'main'
        run: |
          hatch run docs:mike deploy --update-aliases ${HATCH_VERSION} latest

      - name: Deploy mkdocs dev
        if: success() && github.event_name == 'push' && github.ref_name != 'main'
        run: |
          hatch run docs:mike deploy --update-aliases ${HATCH_VERSION} dev

      - name: Success Badge
        if: success()
        run: |
          git checkout gh-pages
          if [ ! -d ${HATCH_VERSION} ]; then mkdir ${HATCH_VERSION}; fi
          echo '{"schemaVersion":1,"label":"Docs","message":"pass","color":"green","namedLogo":"materialformkdocs","logoColor":"white"}' | tee ${HATCH_VERSION}/badge-mkdocs.json

      - name: Fail Badge
        if: success()
        run: |
          git checkout gh-pages
          if [ ! -d ${HATCH_VERSION} ]; then mkdir ${HATCH_VERSION}; fi
          echo '{"schemaVersion":1,"label":"Docs","message":"fail","color":"red","namedLogo":"materialformkdocs","logoColor":"white"}' | tee ${HATCH_VERSION}/badge-mkdocs.json

      - name: Push to Github
        if: always()
        run: |
          git push origin gh-pages
